### ISSUE TITLE
Release 1.8.0 is disabled

### ISSUE THREAD

**Issue by RichWeber** [lajax/yii2-translate-manager#129]
I try to update my version of the extension to the 1.8.0 version and I get next error:

```
Loading composer repositories with package information                                                                                                                                                             Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package lajax/yii2-translate-manager 1.8.0 exists as lajax/yii2-translate-manager[1.0.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.x-dev, dev-master] but these are rejected by your constraint.

```

My composer.json has next configs:

```
"minimum-stability": "dev",
"prefer-stable": true,
```

**Comment by moltam** [comment]
Yes, [packagist](https://packagist.org/packages/lajax/yii2-translate-manager) is not updated for some reason.

**Comment by RichWeber** [comment]
@moltam thanks,
It's a temporary solution for the composer.json

```
"repositories": [
  {
      "type": "git",
      "url": "https://github.com/lajax/yii2-translate-manager.git"
  }
]
```

Hope, you'll find a solution for it soon.

**Comment by moltam** [comment]
I found this on Packagist:

*Existing packages without auto-updating (GitHub/BitBucket hook) will be crawled **once a week** for updates. When a hook is enabled packages are crawled whenever you push, or at least once a month in case the crawl failed. You can also trigger a manual update on your package page if you are logged-in as a maintainer.*

We'll have to wait until the auto-update runs, since I don't have the necessary admin rights to trigger a manual update.

**Comment by RichWeber** [comment]
@moltam thanks
