### ISSUE TITLE
problem in migration (advanced app template)

### ISSUE THREAD

**Issue by ettolo** [lajax/yii2-translate-manager#37]
Hi,
i've installed the translate-manager but i've a problem with migration command:
yii migrate/up --migrationPath=@vendor/lajax/yii2-translate-manager/migrations
i get " unknown property request::cookies " 
deleting language-picker configurations solved the problem

**Comment by moltam** [comment]
I managed to reproduce this: If you put your language-picker config into the common config, and also enable to bootstrap the extension here, you get this error.

The language-picker requires \yii\web\Response which is not present when you use a console app.

I think this not an error with the extension. You could bypass this, if you put the language-picker config into a web based app config folder. If you need to put the config into the common config (because you use the same config with multiple web apps), you can do this also, but don't enable to bootstrap the language-picker in common config, enable bootstrap individually in each of the web app configs.

**Comment by ettolo** [comment]
Great! thank you!
