### ISSUE TITLE
You are not allowed to access this page

### ISSUE THREAD

**Issue by juliang0413** [lajax/yii2-translate-manager#96]
I am using a advanced template and in the url http://site.local/admin/translatemanager/language/list

You are not allowed to access this page. in /var/www/html/base/vendor/lajax/yii2-translate-manager/Module.php:287

**Comment by juliang0413** [comment]
set 'allowedIPs' => ['*'] or 'allowedIPs' => ['127.0.0.1', '::1']

**Comment by robsch** [comment]
@lajax May I ask why this is the default configuration?

**Comment by moltam** [comment]
The Yii 2 team uses the same defaults for multiple modules (for example Debug, and Gii module).

**Comment by robsch** [comment]
@moltam Yes, since it is thought to be used in an development environment. Is the translate-manager intended to be used there too? 

In my case I have integrated it to the backend of an application so translating can be done on the live server. I have tweakt it a bit so some operations require admin permissions. Regular backend users can solely update texts.

It is of course no problem to change the IP. I was just wondering if I possibly use the translate manager modul not as intended and therefore could get into troubles.

**Comment by moltam** [comment]
The extension can be used in production environment too. You have a good point, in this way this extension differs from the Yii modules mentioned above.

I think the default IP restriction is necessary to prevent unauthorized access in production environments, for example when a developer doesn't look up and use these settings. The module is configurable, you can set accepted roles, or IP addresses to restrict access. You can use both, or either of them.
